name: datajam-npc19
channels:
  - conda-forge
dependencies:
  - matplotlib
  - pandas
  - geopandas
  - bokeh
  - shapely
  - fiona
  - seaborn
  - requests
  - pip:
    - gtfsdb
    - -e=git+https://github.com/remix/partridge/#egg=partridge
