name: datajam-npc19
channels:
  - conda-forge
dependencies:
  - pip
  - matplotlib
  - pandas
  - geopandas
  - bokeh
  - shapely
  - fiona
  - seaborn
  - requests
  - jupyter
  - folium
  - pip:
    # - gtfsdb
    - partridge
